# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordinateTransfer
                                 A QGIS plugin
 Coordinate Transfer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-04
        copyright            : (C) 2021 by m
        email                : m
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordinateTransfer class from file CoordinateTransfer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Coordinate_transfer import CoordinateTransfer
    return CoordinateTransfer(iface)
